# Generated by Django 4.1.5 on 2023-01-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_alter_candidate_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='vote1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='vote3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='vote5',
            field=models.IntegerField(default=0),
        ),
    ]
